/**
 * One-off generator for the dot-matrix world map behind the network map: samples a regular
 * lon/lat grid against Natural Earth's land polygons (public domain, via the ISC-licensed
 * world-atlas package) and writes the land cells as run-length rows to
 * src/shared/lib/map/landDots.ts. The runtime never touches TopoJSON; only this script does.
 *
 *   bun run scripts/map/generate-land-dots.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { feature } from "topojson-client";
import type { Topology } from "topojson-specification";
import type { MultiPolygon, Polygon } from "geojson";
import land from "world-atlas/land-50m.json";
import { LAT_MAX, LAT_MIN, LON_MIN, LON_MAX, GRID_STEP } from "../../src/shared/lib/map/projection";

type Ring = [number, number][];

function pointInRing([x, y]: [number, number], ring: Ring): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i]!;
    const [xj, yj] = ring[j]!;
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

function main() {
  const topo = land as unknown as Topology;
  const geo = feature(topo, topo.objects.land!) as unknown as { type: string; geometry?: MultiPolygon | Polygon; features?: { geometry: MultiPolygon | Polygon }[] };
  const geometries = geo.features ? geo.features.map((f) => f.geometry) : [geo.geometry!];
  const rings: Ring[] = [];
  for (const g of geometries) {
    const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
    for (const poly of polys) for (const ring of poly) rings.push(ring as Ring);
  }
  // Even-odd over every ring (outer rings and lake holes alike) gives land membership.
  const isLand = (lon: number, lat: number) => {
    let hits = 0;
    for (const ring of rings) if (pointInRing([lon, lat], ring)) hits += 1;
    return hits % 2 === 1;
  };

  const cols = Math.round((LON_MAX - LON_MIN) / GRID_STEP);
  const rows = Math.round((LAT_MAX - LAT_MIN) / GRID_STEP);
  const runs: number[][] = [];
  let count = 0;
  for (let r = 0; r < rows; r += 1) {
    const lat = LAT_MAX - (r + 0.5) * GRID_STEP;
    const row: number[] = [];
    let start = -1;
    for (let c = 0; c <= cols; c += 1) {
      const lon = LON_MIN + (c + 0.5) * GRID_STEP;
      const on = c < cols && isLand(lon, lat);
      if (on && start < 0) start = c;
      if (!on && start >= 0) {
        row.push(start, c - start);
        count += c - start;
        start = -1;
      }
    }
    runs.push(row);
  }

  const out = `/**
 * Land cells of the dot-matrix world map, generated by scripts/map/generate-land-dots.ts from
 * Natural Earth 1:50m land (public domain). One entry per grid row from LAT_MAX southwards;
 * each row is a flat list of [startColumn, length] runs. Do not edit by hand.
 */
export const LAND_COLS = ${cols};
export const LAND_ROWS = ${rows};
export const LAND_RUNS: readonly (readonly number[])[] = ${JSON.stringify(runs)};
`;
  const target = join(import.meta.dir, "../../src/shared/lib/map/landDots.ts");
  writeFileSync(target, out);
  console.log(`wrote ${target}: ${cols}x${rows} grid, ${count} land dots`);
}

main();
