import type { ThemeDefinition } from "./define";
import { BASE_TOKENS } from "./tokens";

const HEADER =
  "/* Generated by `bun run themes` from src/shared/theme. Do not edit: change the theme files. */\n";

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((line) => `  ${line}`).join("\n")}\n}\n`;
}

function declarations(values: Record<string, string>): string[] {
  return Object.entries(values).map(([name, value]) => `--${name}: ${value};`);
}

/**
 * One rule per theme. `html[data-theme]` outranks the `:root { --primary… }` block the Sage SDK
 * mounts inside the wallet (TASK-095); the bare attribute selector lets any element preview a
 * theme (the settings swatches) by carrying `data-theme` itself.
 */
export function renderThemesCss(themes: readonly ThemeDefinition[]): string {
  const base = block("html:root", declarations(BASE_TOKENS));
  const rules = themes.map((theme) =>
    block(`html[data-theme="${theme.id}"],\n[data-theme="${theme.id}"]`, [
      `color-scheme: ${theme.scheme};`,
      ...declarations(theme.palette),
      ...declarations(theme.tokens),
    ])
  );
  return [HEADER, base, ...rules].join("\n");
}
