/**
 * The theme contract: every token a theme must define. Components only ever read these (through
 * Tailwind's `bg-surface`, `text-fg-muted`… in src/app/globals.css or `var(--…)`), so a new theme
 * is one file under ./themes that fills this list, plus an entry in ./index.ts.
 */
export const THEME_TOKENS = [
  "bg",
  "bg-elevated",
  "surface",
  "surface-2",
  "surface-hover",
  "border",
  "border-strong",
  "rule",
  "map-land",
  "map-bg",
  "map-grid",
  "map-marker-edge",
  "region-europe",
  "region-asia",
  "region-north-america",
  "region-south-america",
  "region-africa",
  "region-oceania",
  "region-unmapped",
  "fg",
  "fg-muted",
  "fg-faint",
  "primary",
  "primary-strong",
  "primary-tint",
  "primary-soft",
  "primary-fg",
  "cta",
  "cta-hover",
  "cta-fg",
  "cta-edge",
  "focus",
  "row-flash",
  "accent",
  "warning",
  "danger",
  "danger-soft",
  "info",
  "fee-0",
  "fee-1",
  "fee-2",
  "fee-3",
  "fee-4",
  "fee-5",
  "block-face",
  "block-side",
  "block-top",
  "block-empty",
  "projected-face",
  "cube-top-hi",
  "cube-side-from",
  "cube-side-to",
  "cube-glass",
  "cube-grid",
  "cube-fill-shade",
  "cube-sheen",
  "cube-waterline",
  "cube-top-line",
  "cube-empty-edge",
  "cube-edge",
  "cube-drop",
  "cube-text-shadow",
  "cube-dash",
  "cube-shade",
  "confirmed-fill",
  "strip-bg",
  "kind-xch",
  "kind-cat",
  "kind-nft",
  "kind-did",
  "kind-offer",
  "kind-unknown",
  "badge-mix",
  "alloc-0",
  "alloc-1",
  "alloc-2",
  "alloc-3",
  "alloc-4",
  "alloc-other",
  "shadow",
  // Effects: how much light and shine a theme carries ("none" or a plain colour for a quiet one).
  "page-glow",
  "glow",
  "sheen",
  "header-line",
] as const;

export type ThemeToken = (typeof THEME_TOKENS)[number];

/** Geometry shared by every theme unless a theme overrides it. */
export const BASE_TOKENS = {
  radius: "12px",
  "radius-sm": "8px",
  "radius-control": "10px",
  "header-h": "72px",
} as const;

export type BaseToken = keyof typeof BASE_TOKENS;
