import { defineTheme } from "../define";

/**
 * Midnight: the original mempoolxch.space look, kept as a choice. Deep navy surfaces, Chia
 * green as the accent, glossy block cubes with a bright waterline, a green light on the top of
 * the page, a sheen travelling over the capacity bars and a green-to-sky hairline under the
 * header. Darker and shinier than the Beidwerk themes on purpose.
 */
export const midnight = defineTheme({
  id: "midnight",
  scheme: "dark",
  /** Raw palette, emitted as `--name` and referenced from the tokens below. */
  palette: {
    navy: "#0f1220",
    "navy-raised": "#1c2033",
    "chia-green": "#5ece7b",
    "chia-green-deep": "#3aac59",
    sky: "#7dd3fc",
    periwinkle: "#8aa4ff",
    orchid: "#d68cf5",
    gold: "#f5c542",
    amber: "#f2903b",
    coral: "#f0616d",
    mist: "#e8ebf5",
  },
  tokens: {
    bg: "var(--navy)",
    "bg-elevated": "#171a2b",
    surface: "var(--navy-raised)",
    "surface-2": "#232842",
    "surface-hover": "#2a3050",
    border: "#2c3350",
    "border-strong": "#3b4468",
    rule: "color-mix(in srgb, var(--mist) 9%, var(--navy-raised))",
    "map-land": "#2f3757",
    "map-bg": "#070d1c",
    "map-grid": "rgb(94 206 123 / 0.06)",
    "map-marker-edge": "rgb(7 13 28 / 0.75)",
    "region-europe": "var(--chia-green)",
    "region-asia": "var(--sky)",
    "region-north-america": "var(--periwinkle)",
    "region-south-america": "var(--gold)",
    "region-africa": "var(--orchid)",
    "region-oceania": "var(--amber)",
    "region-unmapped": "#67708f",
    fg: "var(--mist)",
    "fg-muted": "#9aa3c2",
    "fg-faint": "#8d96b5",
    primary: "var(--chia-green)",
    "primary-strong": "var(--chia-green-deep)",
    "primary-tint": "color-mix(in srgb, var(--chia-green) 40%, var(--navy-raised))",
    "primary-soft": "color-mix(in srgb, var(--chia-green) 14%, transparent)",
    "primary-fg": "#06210f",
    cta: "var(--chia-green)",
    "cta-hover": "#74d98e",
    "cta-fg": "#06210f",
    "cta-edge": "color-mix(in srgb, var(--chia-green) 80%, black)",
    focus: "var(--chia-green)",
    /** The most green a fresh row can carry while every row colour keeps 4.5:1 (TASK-095). */
    "row-flash": "rgb(94 206 123 / 0.06)",
    accent: "var(--sky)",
    warning: "var(--gold)",
    danger: "var(--coral)",
    "danger-soft": "rgb(240 97 109 / 0.14)",
    info: "var(--periwinkle)",
    /** The original fee gradient: grey-blue, green, lime, gold, amber, coral. */
    "fee-0": "#4c5b7b",
    "fee-1": "var(--chia-green-deep)",
    "fee-2": "#8fd35c",
    "fee-3": "var(--gold)",
    "fee-4": "var(--amber)",
    "fee-5": "var(--coral)",
    "block-face": "#1f2540",
    "block-side": "#131730",
    "block-top": "#2a3157",
    "block-empty": "#1a1e33",
    "projected-face": "#17283a",
    "cube-top-hi": "color-mix(in srgb, var(--block-top) 78%, white 14%)",
    "cube-side-from": "color-mix(in srgb, var(--block-side) 85%, black)",
    "cube-side-to": "color-mix(in srgb, var(--block-side) 55%, black)",
    "cube-glass": "color-mix(in srgb, var(--block-face) 88%, transparent)",
    "cube-grid": "rgb(255 255 255 / 0.035)",
    "cube-fill-shade": "rgb(0 0 0 / 0.18)",
    /** Glossy cubes: a lit sheen under a bright waterline. */
    "cube-sheen": "rgb(255 255 255 / 0.1)",
    "cube-waterline": "rgb(255 255 255 / 0.55)",
    "cube-top-line": "rgb(255 255 255 / 0.14)",
    "cube-empty-edge": "inset 0 0 0 1px rgb(255 255 255 / 0.04)",
    "cube-edge":
      "inset 0 0 0 1px rgb(255 255 255 / 0.08), inset 0 -18px 30px -18px rgb(0 0 0 / 0.45)",
    "cube-drop": "0 14px 26px -14px rgb(0 0 0 / 0.7)",
    "cube-text-shadow": "0 1px 2px rgb(0 0 0 / 0.65)",
    "cube-dash": "rgb(255 255 255 / 0.15)",
    "cube-shade": "#000",
    "confirmed-fill": "linear-gradient(165deg, #35a8c9 0%, var(--chia-green-deep) 100%)",
    "strip-bg":
      "linear-gradient(180deg, var(--bg-elevated), color-mix(in srgb, var(--navy) 85%, black))",
    "kind-xch": "var(--chia-green)",
    "kind-cat": "var(--periwinkle)",
    "kind-nft": "var(--orchid)",
    "kind-did": "var(--gold)",
    "kind-offer": "var(--sky)",
    "kind-unknown": "#67708f",
    "badge-mix": "20%",
    "alloc-0": "#008300",
    "alloc-1": "#3987e5",
    "alloc-2": "#d95926",
    "alloc-3": "#9085e9",
    "alloc-4": "#c98500",
    "alloc-other": "#67708f",
    shadow: "0 10px 30px rgb(0 0 0 / 0.35)",
    /** Effects: a green light on the page, a green glow on the next block, sheen, gradient line. */
    "page-glow": "rgb(94 206 123 / 0.12)",
    glow: "rgb(94 206 123 / 0.55)",
    sheen: "linear-gradient(90deg, transparent, rgb(255 255 255 / 0.28), transparent)",
    "header-line":
      "linear-gradient(90deg, transparent, rgb(94 206 123 / 0.55) 30%, rgb(125 211 252 / 0.55) 70%, transparent)",
    ambient: "running",
    radius: "10px",
    "radius-sm": "6px",
  },
});
